use stock;
create table stock(
  id int not null AUTO_INCREMENT,
  company_id varchar(10) not null comment '公司代码',
  company_name varchar(10) not null comment '公司简称',
  stock_code varchar(10) not null unique comment 'A股代码',
  stock_name varchar(10) not null comment 'A股简称',
  stock_start_date date not null comment 'A股上市日期',
  stock_total_share float(16,2) not null comment 'A股总股本(手)',
  stock_share_circulate float(16,2) not null comment 'A股流通股本(手)',
  stock_market smallint(3) not null comment '1.深市主板(szmb) 2.中小企业板(szmse) 3.创业板(szcn) 4.沪市主板(shmb) 5.香港主板(hkmb) 6.香港创业板(hkgem) ',
  stock_market_code varchar(10) not null comment '1.深市主板(szmb) 2.中小企业板(szmse) 3.创业板(szcn) 4.沪市主板(shmb) 5.香港主板(hkmb) 6.香港创业板(hkgem) ',
  stock_market_name varchar(20) not null comment '1.深市主板(szmb) 2.中小企业板(szmse) 3.创业板(szcn) 4.沪市主板(shmb) 5.香港主板(hkmb) 6.香港创业板(hkgem) ',
  data_from varchar(100) not null comment '数据来源：上海交易所（sse），深圳交易所(szse)，巨潮资讯(cninfo)，同花顺(tonghuashun)',
  stock_code_B varchar(10)  comment 'B股代码',
  stock_name_B varchar(10)  comment 'B股简称',
  stock_start_date_B date comment 'B股上市日期',
  stock_total_share_B float(16,2)  comment 'B股总股本',
  stock_share_circulate_B float(16,2)  comment 'B股流通股本',
  company_full_name varchar(100) comment '公司全称',
  company_english_name varchar(300) comment '英文名称',
  company_reg_addr varchar(500) comment '注册地址',
  company_belong_area varchar(10) comment '地区',
  company_belong_province varchar(10)  comment '省份',
  company_belong_city varchar(30)  comment '城市',
  company_belong_industry varchar(20)  comment '所属行业',
  company_website varchar(500) comment '公司网址',
  PRIMARY KEY (id) 
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8